# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  # - name: Home
  #   url: Home
  #   weight: 20
  - name: Recruitment
    url: recruitment
    weight: 30
  - name: Accomplish­ments
    url: "#accomplishments"
    weight: 40
  - name: Member
    url: people
    weight: 45
  # - name: Contact
  #   url: contact
  #   weight: 50
